title: Python and Blockchain Enthusiast
author: Coder T
email: tbn45@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first blog.  It will focus on Python and how Blockchain is 
  used in the legal industry.

# social links
twitter_username: @NkowaneTikwiza
github_username:  Tikwiza

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-architect
